# Translations template for glance.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the glance project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: glance 11.0.0.0b2.dev1\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-06-24 06:10+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: glance/gateway.py:252
msgid ""
"The search and index services are not available. Ensure you have the "
"necessary prerequisite dependencies installed like elasticsearch to use "
"these services."
msgstr ""

#: glance/listener.py:40
#, python-format
msgid ""
"Failed to retrieve supported notification events from search plugins "
"%(ext)s: %(e)s"
msgstr ""

#: glance/location.py:403
#, python-format
msgid ""
"Glance tried all active locations to get data for image %s but all have "
"failed."
msgstr ""

#: glance/notifier.py:362 glance/api/common.py:95
#, python-format
msgid "An error occurred during image.send notification: %(err)s"
msgstr ""

#: glance/scrubber.py:172
#, python-format
msgid "%s file can not be read."
msgstr ""

#: glance/scrubber.py:195
#, python-format
msgid "%s file can not be wrote."
msgstr ""

#: glance/scrubber.py:519
#, python-format
msgid "Can not %(op)s scrub jobs from queue: %(err)s"
msgstr ""

#: glance/api/common.py:58
#, python-format
msgid ""
"An error occurred reading from backend storage for image %(image_id)s: "
"%(err)s"
msgstr ""

#: glance/api/common.py:64
#, python-format
msgid ""
"Backend storage for image %(image_id)s disconnected after writing only "
"%(bytes_written)d bytes"
msgstr ""

#: glance/api/common.py:123
#, python-format
msgid "Invalid value for option user_storage_quota: %(users_quota)s"
msgstr ""

#: glance/api/middleware/cache.py:174
#, python-format
msgid ""
"Image cache contained image file for image '%s', however the registry did"
" not contain metadata for that image!"
msgstr ""

#: glance/api/middleware/cache.py:273
#, python-format
msgid "could not find %s"
msgstr ""

#: glance/api/middleware/cache.py:292
msgid "Checksum header is missing."
msgstr ""

#: glance/api/v1/images.py:621
#, python-format
msgid "Copy from external source '%(scheme)s' failed for image: %(image)s"
msgstr ""

#: glance/api/v1/upload_utils.py:79
#, python-format
msgid "Unable to kill image %(id)s: "
msgstr ""

#: glance/api/v1/upload_utils.py:266
#, python-format
msgid "Received HTTP error while uploading image %s"
msgstr ""

#: glance/api/v2/image_data.py:60
#, python-format
msgid "Unable to restore image %(image_id)s: %(e)s"
msgstr ""

#: glance/api/v2/image_data.py:155 glance/api/v2/image_data.py:159
msgid "Failed to upload image data due to HTTP error"
msgstr ""

#: glance/api/v2/image_data.py:164 glance/api/v3/artifacts.py:313
msgid "Failed to upload image data due to internal error"
msgstr ""

#: glance/api/v2/metadef_namespaces.py:210
#, python-format
msgid "Failed to delete namespace %(namespace)s "
msgstr ""

#: glance/api/v3/artifacts.py:358
#, python-format
msgid "Unable to restore artifact %(artifact_id)s: %(e)s"
msgstr ""

#: glance/artifacts/location.py:132
#, python-format
msgid "Failed to delete blob %(blob_id)s from store: %(exc)s"
msgstr ""

#: glance/artifacts/location.py:166
#, python-format
msgid ""
"Glance tried all active locations to get data for blob %s but all have "
"failed."
msgstr ""

#: glance/async/__init__.py:68
msgid ""
"This execution of Tasks is not setup. Please consult the project "
"documentation for more information on the executors available."
msgstr ""

#: glance/async/__init__.py:72
msgid "Internal error occurred while trying to process task."
msgstr ""

#: glance/async/taskflow_executor.py:130
#, python-format
msgid "Failed to execute task %(task_id)s: %(exc)s"
msgstr ""

#: glance/async/flows/base_import.py:154
#, python-format
msgid "Task: %(task_id)s failed to import image %(image_id)s to the filesystem."
msgstr ""

#: glance/async/flows/base_import.py:343
#, python-format
msgid "Task ID %s"
msgstr ""

#: glance/async/flows/introspect.py:60
#, python-format
msgid "Failed to execute introspection %(task_id)s: %(exc)s"
msgstr ""

#: glance/cmd/index.py:48
#, python-format
msgid "Failed to setup index extension %(ext)s: %(e)s"
msgstr ""

#: glance/common/property_utils.py:81
#, python-format
msgid "Couldn't find property protection file %(file)s: %(error)s."
msgstr ""

#: glance/common/property_utils.py:88
#, python-format
msgid ""
"Invalid value '%s' for 'property_protection_rule_format'. The permitted "
"values are 'roles' and 'policies'"
msgstr ""

#: glance/common/property_utils.py:107
#, python-format
msgid ""
"Multiple policies '%s' not allowed for a given operation. Policies can be"
" combined in the policy file"
msgstr ""

#: glance/common/property_utils.py:120
#, python-format
msgid ""
"Malformed property protection rule in [%(prop)s] %(op)s=%(perm)s: '@' and"
" '!' are mutually exclusive"
msgstr ""

#: glance/common/property_utils.py:145
#, python-format
msgid "Encountered a malformed property protection rule %(rule)s: %(error)s."
msgstr ""

#: glance/common/rpc.py:188
#, python-format
msgid ""
"RPC Call Error: %(val)s\n"
"%(tb)s"
msgstr ""

#: glance/common/store_utils.py:64
#, python-format
msgid "Failed to delete image %(image_id)s from store: %(exc)s"
msgstr ""

#: glance/common/swift_store_utils.py:83
#, python-format
msgid "swift config file %(conf_file)s:%(exc)s not found"
msgstr ""

#: glance/common/swift_store_utils.py:97
msgid "Invalid format of swift store config cfg"
msgstr ""

#: glance/common/utils.py:116
#, python-format
msgid "Error: cooperative_iter exception %s"
msgstr ""

#: glance/common/utils.py:513
msgid ""
"Error setting up the debug environment. Verify that the option "
"pydev_worker_debug_host is pointing to a valid hostname or IP on which a "
"pydev server is listening on the port indicated by "
"pydev_worker_debug_port."
msgstr ""

#: glance/common/wsgi.py:337
#, python-format
msgid "Not respawning child %d, cannot recover from termination"
msgstr ""

#: glance/common/artifacts/loader.py:96
#, python-format
msgid "Unable to load artifacts: %s"
msgstr ""

#: glance/common/artifacts/loader.py:164
#, python-format
msgid "Could not load plugin from %(module)s: %(msg)s"
msgstr ""

#: glance/common/location_strategy/__init__.py:66
#, python-format
msgid "Failed to load location strategy module %(module)s: %(e)s"
msgstr ""

#: glance/common/scripts/__init__.py:40
#, python-format
msgid ""
"This task type %(task_type)s is not supported by the current deployment "
"of Glance. Please refer the documentation provided by OpenStack or your "
"operator for more information."
msgstr ""

#: glance/common/scripts/__init__.py:50
#, python-format
msgid "Failed to save task %(task_id)s in DB as task_repo is %(task_repo)s"
msgstr ""

#: glance/common/scripts/utils.py:47
#, python-format
msgid "Task not found for task_id %s"
msgstr ""

#: glance/db/sqlalchemy/artifacts.py:346
msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr ""

#: glance/db/sqlalchemy/artifacts.py:532
msgid "Cannot use this parameter with the operator IN"
msgstr ""

#: glance/db/sqlalchemy/artifacts.py:539
#, python-format
msgid "Operator %s is not supported"
msgstr ""

#: glance/db/sqlalchemy/metadata.py:194
#, python-format
msgid "Json schema files not found in %s. Aborting."
msgstr ""

#: glance/db/sqlalchemy/metadata.py:460
msgid ""
"To use --prefer_new or --overwrite you need to combine of these options "
"with --merge option."
msgstr ""

#: glance/db/sqlalchemy/metadata.py:465
msgid ""
"Please provide no more than one option from this list: --prefer_new, "
"--overwrite"
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:63
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:97
#, python-format
msgid "Invalid store uri for image: %(image_id)s. Details: %(reason)s"
msgstr ""

#: glance/domain/__init__.py:412
#, python-format
msgid ""
"Task [%(task_id)s] status failed to change from %(cur_status)s to "
"%(new_status)s"
msgstr ""

#: glance/domain/__init__.py:520
#, python-format
msgid "Failed to load the %s executor provided in the config."
msgstr ""

#: glance/image_cache/__init__.py:271
#, python-format
msgid ""
"Exception encountered while tee'ing image '%(image_id)s' into cache: "
"%(error)s. Continuing with response."
msgstr ""

#: glance/image_cache/drivers/sqlite.py:397
#, python-format
msgid "Error executing SQLite call. Got error: %s"
msgstr ""

#: glance/registry/api/v1/images.py:136
msgid "Unable to get images"
msgstr ""

#: glance/registry/api/v1/images.py:354
#, python-format
msgid "Unable to show image %s"
msgstr ""

#: glance/registry/api/v1/images.py:390
#, python-format
msgid "Unable to delete image %s"
msgstr ""

#: glance/registry/api/v1/images.py:442
#, python-format
msgid "Unable to create image %s"
msgstr ""

#: glance/registry/api/v1/images.py:515
#, python-format
msgid "Unable to update image %s"
msgstr ""

#: glance/registry/client/v1/client.py:134
#, python-format
msgid "Registry client request %(method)s %(action)s raised %(exc_name)s"
msgstr ""

#: glance/search/api/v0_1/search.py:254
#, python-format
msgid "Failed to retrieve RBAC filters from search plugin %(ext)s: %(e)s"
msgstr ""

#: glance/tests/functional/v2/test_metadef_resourcetypes.py:99
#, python-format
msgid "Forbidden to create resource type. Reason: %(reason)s"
msgstr ""

